# -*- coding: utf-8 -*-
"""AI1003_assignment .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/158MzmyZvRrw4ZULKltZ7lC5vTO3Mzb1-
"""

from random import randint
import numpy as np

#Boxes A,B,C and D are declared as array with 0 representing Red marbles,1 representing White marble and 2 as Black marbles.
A=[0,1,1,1,1,1,1,2,2,2]
B=[0,0,0,0,0,0,1,1,2,2]
C=[0,0,0,0,0,0,0,0,1,2]
D=[1,1,1,1,1,1,2,2,2,2]

#Two dimensional array arr_event representing two independant event, 1st dimension for choosing box and 2nd dimension for choosing a marble in it 
arr_event=np.array([A,B,C,D])

z=0

#counting no of times red marble appearing 
count_red=0 

#array to count no of times red marble appear in each box index 0 for A, 1 for B and 2 for C 
count=np.array([0,0,0]) 


while(z<1000000):
  var_1=randint(0,3)
  var_2=randint(0,9)
  if(arr_event[var_1][var_2]==0):
    count_red = count_red + 1
    count[var_1] = count[var_1] + 1
  z=z+1
  


print("Probability that drawn red marble is from Box A = ",count[0]/count_red)

print("Probability that drawn red marble is from Box B = ",count[1]/count_red)

print("Probability that drawn red marble is from Box C = ",count[2]/count_red)

"""Assignment1"""